Feat/#34 schedule management
KDT5-MINI-TEAM11/backend pull request #49
Opened 2023-08-04 12:26 UTC by Horaiz-UQ

schedule 기능 수정본 입니다
- PENDING 상태일때 취소하는 기능 수정
- APPOVE 상태인 연차/당직만 화면에 나오게 수정

2023-08-04 13:48 UTC, ahdzlq12 approved these changes
고생하셨습니다!

2023-08-04 13:51 UTC, jy-b commented on src/main/java/com/fastcampus/scheduling/schedule/controller/ScheduleController.java
> +        int currentYear = currentDate.getYear();
parameter로 부터 전달 받은 year로 계산 하셔야 합니다!

현재년도 x

2023-08-04 14:04 UTC, jy-b requested changes

2023-08-04 14:04 UTC, jy-b commented on src/main/java/com/fastcampus/scheduling/schedule/controller/ScheduleController.java
> +        List<Schedule> schedules = scheduleServiceImpl.getAllSchedulesByUserIdAndDate(userId, startDate, endDate);
findByYear로 될꺼 같아요

2023-08-04 14:04 UTC, jy-b commented on src/main/java/com/fastcampus/scheduling/schedule/controller/ScheduleController.java
>          Long userId = Long.valueOf(
현 시점 기준 필요없는 메서드일듯!

2023-08-04 14:04 UTC, jy-b commented on src/main/java/com/fastcampus/scheduling/schedule/controller/ScheduleController.java
>      @GetMapping("/user/schedule/list")
위랑 같아요!

2023-08-05 15:54 UTC, jy-b commented on src/main/java/com/fastcampus/scheduling/schedule/service/ScheduleServiceImpl.java
> +        List<Schedule> allSchedules = scheduleRepository.findByUserIdAndStartDateAfterAndStartDateBefore(userId, startDate, endDate);
SELECT * FROM SCHEDULE_TB WHERE YEAR(STARTDATE) = 2023

이런식으로 년도만 있어도 필터링 할 수 있어요

2023-08-05 15:56 UTC, jy-b commented on src/main/java/com/fastcampus/scheduling/schedule/repository/ScheduleRepository.java
> +    List<Schedule> findSchedulesByState(State state);
1년치 상태에 관계없이 데이터를 뽑아서 전달하면 클라이언트에서 가공해서 사용하실꺼에요
state 구별할 필요 없습니다

2023-08-05 15:59 UTC, jy-b commented on src/main/java/com/fastcampus/scheduling/schedule/repository/ScheduleRepository.java
> +    List<Schedule> findByUserIdAndStartDateAfterAndStartDateBefore(Long userId, LocalDate startDate, LocalDate endDate);
findByUserIdAndYear() -> 유저 아이디별,  년도 이용 필터링 -> 마이 페이지

findAllByYear() -> 전 사용자, 년도 이용 필터링 -> 달력 페이지

이런식이면 좋을거 같아요

2023-08-05 16:01 UTC, jy-b commented on src/main/java/com/fastcampus/scheduling/schedule/controller/ScheduleController.java
> +        @RequestParam(name = "year", required = false) Integer year) {
year은 필수값이니 true로,
exception handler에서 잡으면 될듯!

2023-08-05 16:05 UTC, jy-b commented on src/main/java/com/fastcampus/scheduling/schedule/controller/ScheduleController.java
> +            allSchedules = scheduleServiceImpl.findByAllYear(State.APPROVE);
1년치 state에 관계없이 데이터를 뽑아서 전달하면 클라이언트에서 가공해서 사용하실꺼에요
state 구별할 필요 없습니다

2023-08-05 16:09 UTC, jy-b commented on src/main/java/com/fastcampus/scheduling/schedule/controller/ScheduleController.java
> +        if (year != null) {
아래 참조

2023-08-05 16:10 UTC, jy-b commented on src/main/java/com/fastcampus/scheduling/schedule/controller/ScheduleController.java
> +            return ResponseEntity.ok(ApiResponse.success(ErrorMessage.CANNOT_CANCEL_SCHEDULE));
error상황인데 ok면 안될것 같아요

2023-08-05 16:13 UTC, jy-b requested changes
제대로 설명 못드린거 같아서 죄송합니다
궁금하신거 있으시면 메시지 주세요!

2023-08-05 16:13 UTC, jy-b commented on src/main/java/com/fastcampus/scheduling/schedule/service/ScheduleServiceImpl.java
> +            throw new IllegalArgumentException(ErrorMessage.CANNOT_CANCEL_SCHEDULE);
throw new Exceptionxxx 로 하시면 Try-catch로 안잡으셔도 Global Exception Handler가 잡아줍니당

2023-08-07 06:47 UTC, jy-b approved these changes
LGTM 🦖

2023-08-07 06:47 UTC, merged